---
- name: Get default VPC
  ec2_vpc_net_info:
    profile: "{{profile}}"
    region: "{{region}}"
    vpc_ids: vpc-0fc56c8cf0f2f8833
  register: defaultVPC

- name: Get Kubernetes Cluster VPC
  ec2_vpc_net_info:
    profile: "{{profile}}"
    region: "{{region}}"
    filters:
      "tag:Name" : "{{cluster_name}}"
  register: k8sVPC

- name: Creating security group for RDS
  ec2_group:
    name: rds_security_group
    description: security group for RDS
    vpc_id: "{{ defaultVPC.vpcs[0].vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports: 3306
        cidr_ip: "{{ k8sVPC.vpcs[0].cidr_block }}"
        rule_desc: Access to K8s VPC for 3306
      - proto: tcp
        ports: 3306
        cidr_ip: "{{ defaultVPC.vpcs[0].cidr_block }}"
        rule_desc: Access to default VPC for 3306
  register: rds_security_group

- name: Create RDS
  rds:
    command: create
    region: "{{region}}"
    profile: "{{profile}}"
    db_engine: MySQL
    instance_name: csye7374
    size: "10"
    instance_type: db.t2.micro
    username: root
    password: "{{db_password}}"
    publicly_accessible: "False"
    vpc_security_groups: "{{rds_security_group.group_id}}"
    backup_retention: "0"
  async: 500
  poll: 0   