---
- name: Run on Local
  hosts: localhost
  connection: local
  become: false
  gather_facts: False
  vars_files:
    - vars/main.yml
  
  tasks:
    - name: set kops state store
      set_fact:
        kops_state_store: s3://{{cluster_name}}
        
  roles:
  - role: setup-k8s-cluster
    when: command == "start"

  - role: delete-k8s-cluster
    when: command == "stop"
  
  